development:
  adapter: postgresql
  encoding: utf8
  database: pirala_development
  pool: 5
  username: giuseppe
  password: 12345

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: pirala_test
  pool: 5
  username: giuseppe
  password: 12345

production:
  adapter: postgresql
  encoding: utf8
  database: pirala_production
  pool: 5
  username: giuseppe
  password: 12345