# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a10b9cf32cc02cfcbfaa9e572fc889ec08dbd22a09c433c565b22a978714e3fef09460e9de0760612f9df7c7437e357c9843c366d98c6b1d5350ed175775a55
  google_client_id:  946609361939-l7iqve3or61fji6um9pc9a7inrmm7pjr.apps.googleusercontent.com
  google_client_secret:  XheTJ1KU0nlmjO-651900_V2

test:
  secret_key_base: a8254ee52050508ceaf2ed48acf79972294199e378485c0cf3ee3401dcf280e08f5570951477487b499019419a2ccce8cf2507434b1017626709dda85fd9c66a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id:  946609361939-l7iqve3or61fji6um9pc9a7inrmm7pjr.apps.googleusercontent.com
  google_client_secret:  XheTJ1KU0nlmjO-651900_V2
